version: '3.7'

services:

  serverdice:
    container_name: backend
    build: ./
    command: npm start 
    working_dir: /usr/src/ServerDice
    environment:
        POSTGRES_URI: postgres://lemon:secret@postgres:5432/smart-brain-docker 
        REDIS_URI: redis://redis:6379
    links:
       - postgres
       - redis
    ports: 
       - "3000:3000"
    volumes: 
       - ./:/usr/src/ServerDice


  postgres:
   environment:
        POSTGRES_DB: smart-brain-docker
        POSTGRES_USER: lemon
        POSTGRES_PASSWORD: secret   
        POSTGRES_HOST: postgres
   build: ./postgres
   ports:
     - "5432:5432"

  redis: 
   image: redis
   ports:
     - "6379:6379"
